### ISSUE TITLE
Mysql and Redis connection refused

### ISSUE THREAD

**Issue by gweit** [govigilant/vigilant#6]
Hi,

I tried to start Vigilant locally using Docker as described here: https://govigilant.io/documentation/deployment

4 Containers start, but i get some errors:

Creating docker_mysql_1 ... done
Creating docker_redis_1 ... done
Creating docker_app_1   ... done
Creating docker_horizon_1 ... done
Attaching to docker_redis_1, docker_mysql_1, docker_app_1, docker_horizon_1
app_1      | 
mysql_1    | 2024-09-07 08:29:17+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.39-1.el9 started.
redis_1    | 1:C 07 Sep 2024 08:29:17.760 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1    | 1:C 07 Sep 2024 08:29:17.760 * Redis version=7.4.0, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1    | 1:C 07 Sep 2024 08:29:17.760 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
mysql_1    | 2024-09-07 08:29:17+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
app_1      | In KeyGenerateCommand.php line 100:
app_1      |                                                                                
app_1      |   file_get_contents(): Read of 8256 bytes failed with errno=21 Is a directory  
app_1      |                                                                                
app_1      | 
mysql_1    | 2024-09-07 08:29:17+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.39-1.el9 started.
app_1      | 
mysql_1    | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
redis_1    | 1:M 07 Sep 2024 08:29:17.760 * monotonic clock: POSIX clock_gettime
app_1      | In Connection.php line 813:
app_1      |                                                                                
app_1      |   SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: select t  
app_1      |   able_name as `name`, (data_length + index_length) as `size`, table_comment   
app_1      |   as `comment`, engine as `engine`, table_collation as `collation` from infor  
app_1      |   mation_schema.tables where table_schema = 'forge' and table_type in ('BASE   
app_1      |   TABLE', 'SYSTEM VERSIONED') order by table_name)                             
app_1      |                                                                                
app_1      | 
mysql_1    | 2024-09-07T08:29:18.287616Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
mysql_1    | 2024-09-07T08:29:18.288771Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.39) starting as process 1
redis_1    | 1:M 07 Sep 2024 08:29:17.761 * Running mode=standalone, port=6379.
mysql_1    | 2024-09-07T08:29:18.294207Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
app_1      | In Connector.php line 65:
app_1      |                                              
mysql_1    | 2024-09-07T08:29:18.413300Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
redis_1    | 1:M 07 Sep 2024 08:29:17.762 * Server initialized
redis_1    | 1:M 07 Sep 2024 08:29:17.762 * Loading RDB produced by version 7.4.0
redis_1    | 1:M 07 Sep 2024 08:29:17.762 * RDB age 183 seconds
redis_1    | 1:M 07 Sep 2024 08:29:17.762 * RDB memory usage when created 1.38 Mb
redis_1    | 1:M 07 Sep 2024 08:29:17.762 * Done loading RDB, keys loaded: 0, keys expired: 1.
redis_1    | 1:M 07 Sep 2024 08:29:17.762 * DB loaded from disk: 0.000 seconds
redis_1    | 1:M 07 Sep 2024 08:29:17.762 * Ready to accept connections tcp
app_1      |   SQLSTATE[HY000] [2002] Connection refused  
app_1      |                                              
app_1      | 
mysql_1    | 2024-09-07T08:29:18.591219Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
mysql_1    | 2024-09-07T08:29:18.591266Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
mysql_1    | 2024-09-07T08:29:18.595807Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
app_1      | 
app_1      | In Connection.php line 813:
app_1      |                                                                                
app_1      |   SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: select *  
app_1      |    from `teams`)                                                               
app_1      |                                                                                
app_1      | 
mysql_1    | 2024-09-07T08:29:18.615612Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
mysql_1    | 2024-09-07T08:29:18.615686Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.39'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
app_1      | In Connector.php line 65:
app_1      |                                              
app_1      |   SQLSTATE[HY000] [2002] Connection refused  
app_1      |                                              
app_1      | 
app_1      | Checking Vigilant\Lighthouse\Notifications\Conditions\AccessibilityPercentScoreCondition => Vigilant\Lighthouse\Notifications\Conditions\Category\AccessibilityPercentScoreCondition
app_1      | 
app_1      | In Connection.php line 813:
app_1      |                                                                                
app_1      |   SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: select *  
app_1      |    from `notification_triggers` where JSON_UNQUOTE(JSON_EXTRACT(conditions, '  
app_1      |   $')) LIKE %Vigilant\\\\Lighthouse\\\\Notifications\\\\Conditions\\\\Accessi  
app_1      |   bilityPercentScoreCondition%)                                                
app_1      |                                                                                
app_1      | 
app_1      | In Connector.php line 65:
app_1      |                                              
app_1      |   SQLSTATE[HY000] [2002] Connection refused  
app_1      |                                              
app_1      | 
app_1      | 2024-09-07 08:29:29,304 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
app_1      | 2024-09-07 08:29:29,305 INFO supervisord started with pid 25
app_1      | 2024-09-07 08:29:30,310 INFO spawned: 'cron' with pid 26
app_1      | 2024-09-07 08:29:30,312 INFO spawned: 'octane' with pid 27
app_1      | 
app_1      |    INFO  Server running…
app_1      | 
app_1      |   Local: http://127.0.0.1:8000 
app_1      | 
app_1      |   Press Ctrl+C to stop the server
app_1      | 
app_1      | 2024-09-07 08:29:31,740 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
app_1      | 2024-09-07 08:29:31,740 INFO success: octane entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
horizon_1  | 
horizon_1  |    INFO  Horizon started successfully.  
horizon_1  | 
app_1      | 
app_1      | In PhpRedisConnector.php line 159:
app_1      |                       
app_1      |   Connection refused  
app_1      |                       
app_1      | 
app_1      | 
app_1      | In PhpRedisConnector.php line 159:
app_1      |                       
app_1      |   Connection refused  
app_1      |                       
app_1      | 
app_1      | 
app_1      | In PhpRedisConnector.php line 159:
app_1      |                       
app_1      |   Connection refused  
app_1      |                       
app_1      | 
app_1      | 
app_1      | In PhpRedisConnector.php line 159:
app_1      |                       
app_1      |   Connection refused  
app_1      |                       
app_1      | 
redis_1    | 1:M 07 Sep 2024 08:33:22.281 * 10000 changes in 60 seconds. Saving...
redis_1    | 1:M 07 Sep 2024 08:33:22.281 * Background saving started by pid 71
redis_1    | 71:C 07 Sep 2024 08:33:22.285 * DB saved on disk
redis_1    | 71:C 07 Sep 2024 08:33:22.285 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
redis_1    | 1:M 07 Sep 2024 08:33:22.383 * Background saving terminated with success

Is this maybe a known bug?

**Comment by VincentBean** [comment]
Yes there is a small error in the compose file on the docs.

```yaml
services:
    app:
        image: ghcr.io/govigilant/vigilant:latest
        volumes:
            - .env.docker:/app/.env
```

It mounts `.env.docker` instead of `.env`. Could modfiy this line to `- .env:/app/.env` ?

**Comment by gweit** [comment]
@VincentBean thank you very much, works as expected now.
